app:
  name: "Threat Analysis App"
  secret_key: "secret"
  jwt_algorithm: "HS256"

aws:
  region: "us-east-1"
  credentials:
    access_key_id: "ASIAQLAZOXNL5NISXEZP"
    secret_access_key: "mX5jnYrEf1dIGOpRlodAfQ+785uvhUl3UKIymM4p"
    session_token: "IQoJb3JpZ2luX2VjEKr//////////wEaCXVzLWVhc3QtMSJHMEUCIC6xi90dnSL09ejORJQrfHH681+JUFuu+VO8ik/qoy4pAiEAzKSMbHGdoUpP5YYPJZye5oG9d2GQiO5SpLYcvRr7B90qmgMIov//////////ARAAGgwwMjM2NzU3MTQzOTEiDIe8k7bWGzIaiJ2MZyruArl6gPMGwuGok2I96oOXRI1fr8LFtQ+WpFwZf3wHqLHPxrnZTdTdXA56/gt4mMwKdscsj7JQRX7RdeDEl3kWcQTcekTNnpQLWy5mU1DKKO4esHbg1/tnu30uzntfyBmxxZSQG/XANdETggbzc66gVGoTzEbMp97teMOLtJNhairvIF5Mx/rFZwfypRmAxePBDqyrN1nLbdW1iheu+atwAj1PzpZOqH1c1WC4UG9V7Ui6pQ2BUZy3DjapFu24iOVHc6NdmlodbdUC3fuEVMgbJ/G/tfMtZq4ccMILWRVeWC+4E9bHTi23QT6UmwJCue5AzwGevZpKsXLTiiEkiHX/TIjmypFaddeKPuMF0abrq+3DhzpQ0uB+5hYYWp6VYf1vuBdqYugOTqGHXLWcGgg9v1g+enIE1yztBKkKarI2HNkvG8eCIdfe3nQqMRBZ/W1oz7csMefK+o3bW63SaCxBiewXsTUq5Y6eImL0f+feqTC7p7i8BjqmAcMTGqMNiwQOBpgBcBBXqVWHkJMCcT98B2KJzj3FYede/e0Q+bKOl6vpLIwiSFrD3M7mgyV6XUSedYMgvlw+JDUHzcjNQ+ui7k38oktZWZv+4uqNxcPOzDxgNNZgVqDPVhr03ZSBK7fLZG3tAdmlZWvtHSWUSCV7LvmAqk3cPp254Dp9EMzla+nMEPDClaV8Drfy/FTpKhwtON2hpo+Jffe5BpWdbVU="
  dynamodb:
    users_table: "Users"
    assistants_table: "Assistants"
    chat_sessions_table: "ChatSessions"
    chat_messages_table: "ChatMessages"
    lookup_table: "reverse-index-lookup-template-updated"
    index_id_table: "hpe_sdf_reverse_indexing_lookup_status"
  s3:
    bucket_name: "hpe-data-fabric-genai"
    object_key: "OCSF_schema_v2.json"
  opensearch:
    url: "https://qplcpihjc3mli5hohxee.us-east-1.aoss.amazonaws.com"
    index_name: "hpe-threat-category-embedding-with-text-updated"
  bedrock:
    model_id: "anthropic.claude-3-sonnet-20240229-v1:0"
    temperature: 0.7

langgraph:
  memory_saver: "enabled"
